export const JOI_ERRORS = {
  ANY_REQUIRED: 'any.required',
  NUMBER_BASE: 'number.base',
  NUMBER_DECIMAL: 'number.decimal',
  NUMBER_INTEGER: 'number.integer',
  NUMBER_MIN: 'number.min',
  NUMBER_POSITIVE: 'number.positive',
  NUMBER_RANGE: 'number.range',
  STRING_EMPTY: 'string.empty',
  STRING_PATTERN_BASE: 'string.pattern.base',
  CUSTOM_START_DATE_INVALID: 'custom.startDate.invalid',
  CUSTOM_END_DATE_INVALID: 'custom.endDate.invalid',
  CUSTOM_START_DATE_TODAY_OR_FUTURE: 'custom.startDate.todayOrFuture',
  CUSTOM_END_DATE_TODAY_OR_FUTURE: 'custom.endDate.todayOrFuture',
  CUSTOM_END_DATE_BEFORE_START_DATE: 'custom.endDate.before.startDate',
  CUSTOM_START_DATE_MISSING: 'custom.startDate.missing',
  CUSTOM_END_DATE_MISSING: 'custom.endDate.missing',
  ACTIVITY_START_DATE_DAY: 'activity-start-date-day',
  ACTIVITY_START_DATE_MONTH: 'activity-start-date-month',
  ACTIVITY_START_DATE_YEAR: 'activity-start-date-year',
  ACTIVITY_END_DATE_DAY: 'activity-end-date-day',
  ACTIVITY_END_DATE_MONTH: 'activity-end-date-month',
  ACTIVITY_END_DATE_YEAR: 'activity-end-date-year'
}
