name: Journey Tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
jobs:
  test:
    uses: DEFRA/marine-licensing-journey-tests/run-journey-tests@main